Removed the "Rebuild uses latest changes" messages.
Unity-Technologies/katana pull request #230
Opened 2016-10-20 14:07 UTC by BarryUnity

Testing revealed that Rebuild _always_ uses the revision that the original build used. In that regard, the message saying that a rebuild will use the latest changes when rebuilding from certain builds was wrong. I don't think it needs a replacement.

2016-10-20 14:10 UTC, BarryUnity commented on www/templates/forms.html
> +{% macro rebuild_build(rebuild_url, authz, ss, builderName, url) %}
Can someone confirm that there's no consequences to removing this 'exactly' parameter? I couldn't find rebuild_build being used anywhere else in the code myself.

2016-10-20 16:50 UTC, campos-ddc commented
That tooltip is misleading because the problems it exposes are actually related to the "Build latest" button, and not the "Rebuild" button.

I think that the confusion we have to solve here is the difference between those two. In slack I suggested `"Rebuid" will trigger a new build using the same revision as the last build. If you want to rebuild using the latest revision on branch X, press "Build Latest"`, what do you guys think about that?

2016-10-20 17:01 UTC, mariangemarcano requested changes
@BarryUnity it looks to me that exactly is not longer used, but I think that logic was added by @opdude so better double check it with him.

I dont see any .js changes so remove the changes pushed in .js files as they are not required for .html changes

2016-10-20 17:05 UTC, mariangemarcano commented
@campos-ddc that message looks fine to me

2016-10-20 17:10 UTC, opdude commented
@mariangemarcano according to blame that came in from our merge from upstream. So no idea, looking at the code I think it's fine

2016-10-21 11:22 UTC, BarryUnity commented
@campos-ddc is that not going overboard? I mean the message "To force a rebuild with the same source revisions and parameters used in this build, click the 'Rebuild' button" is still there. Is the button labelled 'build latest' really so vague that it needs an explanation for what it does?

2016-10-21 13:19 UTC, mariangemarcano approved these changes

2016-10-21 13:25 UTC, merged