Change page titles
Unity-Technologies/katana pull request #269
Opened 2017-08-03 13:47 UTC by takarzyna

https://jira.hq.unity3d.com/browse/CDS-698

Removed 'Katana -' from page titles and added branch name to Builders page.
Should the branch name be shown on any other page?

2017-08-03 14:55 UTC, takarzyna commented on master/buildbot/status/web/builder.py
> +            if len(branch) > 0:
not checking for KeyError (missing 'branch'), because if it's missing Katana breaks somewhere else anyway

2017-08-03 15:06 UTC, takarzyna commented on master/buildbot/status/web/builder.py
> +                branch_name = branch[0] + ' '
apparently it's a list with a single value? Correct me if I'm wrong.

2017-08-10 09:41 UTC, sualitu approved these changes

2017-08-22 08:10 UTC, mariangemarcano requested changes

2017-08-22 08:10 UTC, mariangemarcano commented on master/buildbot/status/web/builder.py
> +        self.pageTitle = self.getBranchName() + "Builders"
if the user has a different branch selected (and not the default one) this approach won't work. @sualitu I'll revert this logic from the pr.

2017-08-22 08:35 UTC, mariangemarcano approved these changes

2017-08-22 08:40 UTC, merged