[CDSK-717] Fix status label and add status sorting
Unity-Technologies/katana pull request #338
Opened 2018-03-07 06:59 UTC by Mowinski

I've fixed status label. Also, I've added a sorting of dependencies by statuses.

![t](https://user-images.githubusercontent.com/4771380/37077863-1d4e482c-21dd-11e8-9ddb-1e1b5739d104.png)

2018-03-07 07:10 UTC, warcholprzemo requested changes

2018-03-07 07:10 UTC, warcholprzemo commented on www/script/test/test_helpers.js
> +    it("sort result passed as object by 'order' key", function() {
Duplicated test

2018-03-07 07:14 UTC, warcholprzemo approved these changes

2018-03-07 08:58 UTC, campos-ddc commented
Make sure to use uppercase JIRA project name on the next branch (`CDSK-717-fix-bug`)

Also, `fix-bug` is not a very useful branch name :P

2018-03-07 09:00 UTC, campos-ddc approved these changes

2018-03-07 09:40 UTC, campos-ddc commented
https://unity.slack.com/archives/G9AD6RWES/p1520414765000005

I can no longer see the dependency names next to their status

I noticed that on your screenshots, but I thought that was just something with your local Katana instance

2018-03-07 09:41 UTC, campos-ddc commented
https://unity.slack.com/archives/G9AD6RWES/p1520414961000371

All builds that show as "Waiting for dependency" are actually waiting for an agent for themselves (the build page says "Build will resume", which is closer to the real behavior). That status should probably be "Waiting for available slave" instead of "Waiting for dependency"

2018-03-07 09:41 UTC, campos-ddc commented
https://unity.slack.com/archives/G9AD6RWES/p1520415038000153

This failed build doesn't show any step information https://staging-katana.bf.unity3d.com/projects/Unity/builders/proj0-Test%20GraphicsTests%20-%20Linux32Standalone%20OpenGL%20%28Core%29/builds/445?unity_branch=trunk

2018-03-07 09:42 UTC, campos-ddc commented
https://unity.slack.com/archives/G9AD6RWES/p1520415209000467

Some builds do not show the dependency information.

I have a feeling that is because the dependencies were merged against other running builds

For cases like this, you should look for the dependency `buildrequestid`, but if that buildrequest has a `mergebrid` we should show the information for the request we merged into

2018-03-07 09:42 UTC, campos-ddc commented
https://unity.slack.com/archives/G9AD6RWES/p1520415430000143

Builds that are *actually* waiting for dependency are showing up as RUNNING, not sure how we can actually detect if it is waiting for dependencies, perhaps look for running status and check if the current step is a Trigger step?

2018-03-07 12:26 UTC, Mowinski commented
I've updated screenshot

2018-03-12 12:33 UTC, campos-ddc commented on www/prod/css/default.css
> +.waiting-for-dependency{background-color:#FCFACB}
Should this be renamed to `waiting-for-available-slave`?

2018-03-14 09:59 UTC, merged