CDSK-838 - do subordering (by name) in Dependecies list
Unity-Technologies/katana pull request #341
Opened 2018-03-14 11:09 UTC by warcholprzemo

as in title

2018-03-14 11:40 UTC, campos-ddc approved these changes

2018-03-15 08:34 UTC, Mowinski requested changes

2018-03-15 08:34 UTC, Mowinski commented on www/script/project/helpers.js
> +                if(a[1] == b[1])
Could you do equality without type conversion, I mean `===`.
The difference between this both is the following:
* equality symbol `==` compare a value of objects, so if you compare `0 == ""` you'll get `true`, so javascript do an implicit conversion of objects.
* equality symbol without conversion `===` compare type and value of objects, it means that `0 === ""` is not true

2018-03-15 08:53 UTC, Mowinski approved these changes

2018-03-15 08:54 UTC, merged